-- Customer Table
CREATE TABLE IF NOT EXISTS `customers` (
  `id` int NOT NULL AUTO_INCREMENT,
  `customer_code` varchar(50) NOT NULL,
  `customer_name` varchar(100) NOT NULL,
  `contact_person` varchar(50) NOT NULL,
  `contact_phone` varchar(20) NOT NULL,
  `contact_email` varchar(100),
  `company_address` varchar(500),
  `customer_type` varchar(20) DEFAULT 'regular',
  `credit_rating` varchar(10) DEFAULT 'A',
  `credit_limit` decimal(10, 2) DEFAULT 0.00,
  `total_orders` int DEFAULT 0,
  `total_amount` decimal(15, 2) DEFAULT 0.00,
  `last_order_date` date,
  `status` varchar(20) DEFAULT 'active',
  `remarks` text,
  `created_by` int,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_customer_code` (`customer_code`),
  KEY `idx_customer_name` (`customer_name`),
  KEY `idx_status` (`status`),
  KEY `idx_customer_type` (`customer_type`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Service Request Table
CREATE TABLE IF NOT EXISTS `service_requests` (
  `id` int NOT NULL AUTO_INCREMENT,
  `request_no` varchar(50) NOT NULL,
  `customer_id` int NOT NULL,
  `request_type` varchar(50) NOT NULL,
  `request_title` varchar(200) NOT NULL,
  `request_content` text NOT NULL,
  `priority` varchar(20) DEFAULT 'normal',
  `status` varchar(20) DEFAULT 'pending',
  `handler_id` int,
  `handler_name` varchar(50),
  `handle_time` datetime,
  `handle_result` text,
  `customer_satisfaction` int,
  `response_time` int,
  `resolve_time` int,
  `attachments` varchar(500),
  `created_by` int,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_request_no` (`request_no`),
  KEY `idx_customer_id` (`customer_id`),
  KEY `idx_status` (`status`),
  KEY `idx_priority` (`priority`),
  KEY `idx_request_type` (`request_type`),
  CONSTRAINT `service_requests_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Shipment Plan Table
CREATE TABLE IF NOT EXISTS `shipment_plans` (
  `id` int NOT NULL AUTO_INCREMENT,
  `plan_no` varchar(50) NOT NULL,
  `plan_name` varchar(200) NOT NULL,
  `customer_id` int NOT NULL,
  `order_id` int,
  `goods_type` varchar(100) NOT NULL,
  `goods_name` varchar(200) NOT NULL,
  `goods_quantity` decimal(10, 2) NOT NULL,
  `goods_weight` decimal(10, 2) NOT NULL,
  `goods_volume` decimal(10, 2) NOT NULL,
  `pickup_address` varchar(500) NOT NULL,
  `delivery_address` varchar(500) NOT NULL,
  `pickup_date` date NOT NULL,
  `delivery_date` date NOT NULL,
  `vehicle_type` varchar(50),
  `driver_id` int,
  `transport_mode` varchar(50) DEFAULT 'road',
  `estimated_cost` decimal(10, 2),
  `actual_cost` decimal(10, 2),
  `special_requirements` text,
  `status` varchar(20) DEFAULT 'draft',
  `progress` int DEFAULT 0,
  `remarks` text,
  `created_by` int,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plan_no` (`plan_no`),
  KEY `idx_customer_id` (`customer_id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_status` (`status`),
  KEY `idx_pickup_date` (`pickup_date`),
  KEY `idx_delivery_date` (`delivery_date`),
  CONSTRAINT `shipment_plans_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE CASCADE,
  CONSTRAINT `shipment_plans_ibfk_2` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE SET NULL,
  CONSTRAINT `shipment_plans_ibfk_3` FOREIGN KEY (`driver_id`) REFERENCES `drivers` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
