-- Driver Table
CREATE TABLE IF NOT EXISTS `drivers` (
  `id` int NOT NULL AUTO_INCREMENT,
  `driver_name` varchar(50) NOT NULL,
  `phone` varchar(20) NOT NULL,
  `id_card` varchar(18) DEFAULT NULL,
  `license_no` varchar(50) DEFAULT NULL,
  `license_type` varchar(20) DEFAULT NULL,
  `license_expire_date` date DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `emergency_contact` varchar(50) DEFAULT NULL,
  `emergency_phone` varchar(20) DEFAULT NULL,
  `status` enum('active','inactive','on_leave') DEFAULT 'active',
  `hire_date` date DEFAULT NULL,
  `total_mileage` decimal(10,2) DEFAULT '0.00',
  `total_orders` int DEFAULT '0',
  `rating` decimal(3,2) DEFAULT '5.00',
  `avatar` varchar(255) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_phone` (`phone`),
  KEY `idx_status` (`status`),
  KEY `idx_driver_name` (`driver_name`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Transport Documents Table
CREATE TABLE IF NOT EXISTS `transport_documents` (
  `id` int NOT NULL AUTO_INCREMENT,
  `document_no` varchar(50) NOT NULL,
  `document_type` enum('packing_list','delivery_note','invoice','waybill','receipt','other') NOT NULL,
  `order_id` int DEFAULT NULL,
  `driver_id` int DEFAULT NULL,
  `vehicle_id` int DEFAULT NULL,
  `document_title` varchar(200) NOT NULL,
  `file_path` varchar(500) DEFAULT NULL,
  `file_name` varchar(255) DEFAULT NULL,
  `file_size` bigint DEFAULT NULL,
  `file_type` varchar(50) DEFAULT NULL,
  `status` enum('draft','pending_review','approved','rejected','archived') DEFAULT 'draft',
  `created_by` int DEFAULT NULL,
  `reviewed_by` int DEFAULT NULL,
  `review_time` timestamp NULL DEFAULT NULL,
  `review_comment` text DEFAULT NULL,
  `issue_date` date DEFAULT NULL,
  `expire_date` date DEFAULT NULL,
  `is_compliant` tinyint DEFAULT '1',
  `compliance_check_result` text DEFAULT NULL,
  `remark` text DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_document_no` (`document_no`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_driver_id` (`driver_id`),
  KEY `idx_vehicle_id` (`vehicle_id`),
  KEY `idx_document_type` (`document_type`),
  KEY `idx_status` (`status`),
  KEY `idx_issue_date` (`issue_date`),
  CONSTRAINT `transport_documents_ibfk_1` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE SET NULL,
  CONSTRAINT `transport_documents_ibfk_2` FOREIGN KEY (`driver_id`) REFERENCES `drivers` (`id`) ON DELETE SET NULL,
  CONSTRAINT `transport_documents_ibfk_3` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicles` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
